backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: "Pages"
    name: "pages"
    # create: true
    # editor:
    #   preview: true
    files:
      - label: "About Page"
        name: "about"
        file: "assets/content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      # - label: "Locations Page"
      #   name: "locations"
      #   file: "site/content/locations.yml"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Intro, name: intro, widget: markdown}
      #     - label: Locations
      #       name: locations
      #       widget: list
      #       fields:
      #         - {label: Name, name: name, widget: string}
      #         - {label: Address, name: address, widget: string}